version: "3.9"

services:
  base:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: enumc:dev
    volumes:
      - ./build:/usr/src/app/build
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock:delegated

